{
 "title": "Individual Host Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "HOST",
    "label": "Host",
    "query": "select name from entity where type = 'PHYSICAL_MACHINE' order by 1"
   },
   {
    "name": "HOST_OID",
    "query": "select oid from entity where name = '$HOST' and type = 'PHYSICAL_MACHINE' order by last_seen DESC limit 1"
   },
   {
    "name": "TARGET_TYPE",
    "query": "SELECT\njsonb_array_elements(attrs->'targets')->>'type'\nFROM entity\nWHERE oid = $HOST_OID"
   },
   {
    "name": "TARGET_NAME",
    "query": "SELECT\njsonb_array_elements(attrs->'targets')->>'name'\nFROM entity\nWHERE oid = $HOST_OID"
   },
   {
    "name": "TARGET_CATEGORY",
    "query": "SELECT\njsonb_array_elements(attrs->'targets')->>'category'\nFROM entity\nWHERE oid = $HOST_OID"
   },
   {
    "name": "HOST_STATE",
    "query": "SELECT\nCASE WHEN int_value::entity_state = 'POWERED_ON' THEN 'Powered On' \nELSE 'Powered Off'\nEND\nFROM historical_entity_attrs\nWHERE entity_oid = $HOST_OID\nAND type = 'ENTITY_STATE'\nORDER by time DESC limit 1"
   },
   {
    "name": "HOST_CLUSTER",
    "query": "select e.\"name\" \nfrom \"scope\" s\njoin entity e on e.oid = s.scoped_oid \nwhere seed_oid = $HOST_OID\nand scoped_type = 'COMPUTE_CLUSTER'\nand finish > now()"
   },
   {
    "name": "HOST_DATACENTER",
    "query": "select e.\"name\" \nfrom \"scope\" s\njoin entity e on e.oid = s.scoped_oid \nwhere seed_oid = $HOST_OID\nand scoped_type = 'DATACENTER'\nand finish > now()"
   },
   {
    "name": "HOST_MODEL",
    "query": "select attrs->>'model' from entity e where oid = $HOST_OID"
   },
   {
    "name": "HOST_CPU_MODEL",
    "query": "select attrs->>'cpu_model' from entity e where oid = $HOST_OID"
   },
   {
    "name": "HOST_NUM_CPUS",
    "query": "select attrs->>'num_cpus' from entity e where oid = $HOST_OID"
   },
   {
    "name": "HOST_MEMORY_CURGBCAPACITY",
    "query": "select round(capacity/1024/1024) from metric\nwhere entity_oid = $HOST_OID\nand type = 'MEM'\nORDER by time DESC limit 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Host Identity Card",
   "type": "text",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n\nThe Host is currently <b>$HOST_STATE</b>.\n<br /><br />\n\n<table>\n    <thead>\n        <tr>\n            <td><b>Name</b></td>\n            <td><b>Cluster</b></td>\n            <td><b>Datacenter</b></td>\n            <td><b>Target Name</b></td>\n            <td><b>Target Type</b></td>\n        </tr>\n    </thead>\n    <tbody>\n        <tr>\n            <td>${HOST}</td>\n            <td>${HOST_CLUSTER}</td>\n            <td>${HOST_DATACENTER}</td>\n            <td>${TARGET_NAME}</td>\n            <td>${TARGET_TYPE}</td>\n        </tr>\n    </tbody>\n</table>\n<br />\n<table>\n    <thead>\n        <tr>\n            <td><b>Model</b></td>\n            <td><b>Number of CPUs</b></td>\n            <td><b>CPU Model</b></td>\n            <td><b>Quantity of Memory (Gb)</b></td>\n        </tr>\n    </thead>\n    <tbody>\n        <tr>\n            <td>${HOST_MODEL}</td>\n            <td>${HOST_NUM_CPUS}</td>\n            <td>${HOST_CPU_MODEL}</td>\n            <td>${HOST_MEMORY_CURGBCAPACITY}</td>\n        </tr>\n    </tbody>\n</table>\n</center>\n\n"
   }
  },
  {
   "title": "Current Group Membership",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "select e.name from \"scope\" s\njoin entity e on s.scoped_oid = e.oid\nwhere s.seed_oid = $HOST_OID\nand s.scoped_type = 'GROUP'\nand s.finish >= $__timeTo()\norder by e.name"
    }
   ]
  },
  {
   "title": "CPU & Mem Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"type\" as metric,\n  utilization as value\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  (type = 'CPU' or type = 'MEM') AND\n  entity_oid = $HOST_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ready Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  utilization as value,\n  \"type\" as metric\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  (type IN ('CPU_READY','Q1_VCPU','Q2_VCPU','Q4_VCPU','Q8_VCPU','Q16_VCPU','Q32_VCPU','Q64_VCPU')) AND\n  entity_oid = $HOST_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Swapping - Ballooning",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "B/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  utilization as value,\n  \"type\" as metric\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  (type IN ('SWAPPING','BALLOONING')) AND\n  entity_oid = $HOST_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Storage Latency Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  consumed\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  type = 'STORAGE_LATENCY' AND\n  entity_oid = $HOST_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Storage Access Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "KB/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  consumed\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  type = 'STORAGE_ACCESS' AND\n  entity_oid = $HOST_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Storage IOPS Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "iops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  utilization\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  type = 'IO_THROUGHPUT' AND\n  entity_oid = $HOST_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "KB/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  utilization\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  type = 'NET_THROUGHPUT' AND\n  entity_oid = $HOST_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pending Actions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"time\",\n  count(type) as value,\n  CONCAT(category,' - ',type) as metric\nFROM pending_action\nWHERE\n  involved_entities @> '{\"$HOST_OID\"}'\nGROUP BY 1, 3\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Performance actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Time\",\n  description AS \"Description\"\nFROM pending_action\nWHERE\n  (category = 'PERFORMANCE_ASSURANCE' OR category = 'PREVENTION') AND\n  involved_entities @> '{\"$HOST_OID\"}'\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Efficiency actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Time\",\n  description AS \"Description\"\nFROM pending_action\nWHERE\n  (category = 'EFFICIENCY_IMPROVEMENT') AND\n  involved_entities @> '{\"$HOST_OID\"}'\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Compliance actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Time\",\n  description AS \"Description\"\nFROM pending_action\nWHERE\n  (category = 'COMPLIANCE') AND\n  involved_entities @> '{\"$HOST_OID\"}'\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Performance actions",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Time\",\n  description AS \"Description\"\nFROM pending_action\nWHERE\n  (category = 'PERFORMANCE_ASSURANCE' OR category = 'PREVENTION') AND\n  involved_entities @> '{\"$HOST_OID\"}'\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Efficiency actions",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Time\",\n  description AS \"Description\"\nFROM pending_action\nWHERE\n  category = 'EFFICIENCY_IMPROVEMENT' AND\n  involved_entities @> '{\"$HOST_OID\"}'\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Compliance actions",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Time\",\n  description AS \"Description\"\nFROM pending_action\nWHERE\n  category = 'COMPLIANCE' AND\n  involved_entities @> '{\"$HOST_OID\"}'\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Past taken actions",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  description AS \"Description\",\n  acceptance_time AS \"Acceptance Time\",\n  recommendation_time as \"Recommendation Time\",\n  final_state as \"Final State\",\n  \"type\" as \"Type\",\n  category as \"Category\",\n  savings as \"Savings\"\nFROM completed_action\nWHERE\n  $__timeFilter(\"acceptance_time\") AND\n  involved_entities @> '{\"$HOST_OID\"}'\nORDER BY acceptance_time DESC"
    }
   ]
  },
  {
   "title": "Related VMs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "panelId": 37 }
   ]
  },
  {
   "title": "Related VMs",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 53 },
   "targets": [
    {
     "rawSql": "select distinct\n\te.oid as \"OID\",\n\te.name as \"Name\",\n\tTO_CHAR(e.first_seen, 'dd/mm/yyyy hh:mm:ss') as \"First seen\",\n\tCASE WHEN TO_CHAR(e.last_seen, 'dd/mm/yyyy hh:mm:ss') = '31/12/9999 12:12:00' THEN 'Still present' ELSE TO_CHAR(e.last_seen, 'dd/mm/yyyy hh:mm:ss') END  as \"Last seen\"\nfrom scope s \njoin entity e on s.scoped_oid = e.\"oid\" \nwhere s.seed_oid = $HOST_OID\nand s.scoped_type = 'VIRTUAL_MACHINE'\nand\n  (\n    (s.start <= $__timeFrom() and s.finish <= $__timeTo()) or\n    (s.start >= $__timeFrom() and s.finish <= $__timeTo()) or\n    (s.start >= $__timeFrom() and s.finish >= $__timeTo()) or\n    (s.start <= $__timeFrom() and s.finish >= $__timeTo())\n  )\nand s.finish >= $__timeFrom()\nand s.start <= $__timeTo()\norder by e.name"
    },
    {
     "rawSql": "select distinct\n\te.oid as \"OID\",\n\tm.\"type\" as \"Type\",\n\tcoalesce(avg(m.utilization), avg(m.consumed))\tas \"Utilization\"\nfrom scope s \njoin entity e on s.scoped_oid = e.\"oid\" \njoin metric m on m.entity_oid = e.\"oid\" AND $__timeFilter(m.time)\nwhere s.seed_oid = $HOST_OID\nand s.scoped_type = 'VIRTUAL_MACHINE'\nand\n  (\n    (s.start <= $__timeFrom() and s.finish <= $__timeTo()) or\n    (s.start >= $__timeFrom() and s.finish <= $__timeTo()) or\n    (s.start >= $__timeFrom() and s.finish >= $__timeTo()) or\n    (s.start <= $__timeFrom() and s.finish >= $__timeTo())\n  )\nand s.finish >= $__timeFrom()\nand s.start <= $__timeTo()\nand m.\"type\" IN ('VCPU')\ngroup by e.oid, m.type"
    },
    {
     "rawSql": "select distinct\n\te.oid as \"OID\",\n\tm.\"type\" as \"Type\",\n\tcoalesce(avg(m.utilization), avg(m.consumed))\tas \"Utilization\"\nfrom scope s \njoin entity e on s.scoped_oid = e.\"oid\" \njoin metric m on m.entity_oid = e.\"oid\" AND $__timeFilter(m.time)\nwhere s.seed_oid = $HOST_OID\nand s.scoped_type = 'VIRTUAL_MACHINE'\nand\n  (\n    (s.start <= $__timeFrom() and s.finish <= $__timeTo()) or\n    (s.start >= $__timeFrom() and s.finish <= $__timeTo()) or\n    (s.start >= $__timeFrom() and s.finish >= $__timeTo()) or\n    (s.start <= $__timeFrom() and s.finish >= $__timeTo())\n  )\nand s.finish >= $__timeFrom()\nand s.start <= $__timeTo()\nand m.\"type\" IN ('VMEM')\ngroup by e.oid, m.type"
    },
    {
     "rawSql": "select distinct\n\te.oid as \"OID\",\n\tm.\"type\" as \"Type\",\n\tcoalesce(avg(m.utilization), avg(m.consumed))\tas \"Utilization\"\nfrom scope s \njoin entity e on s.scoped_oid = e.\"oid\" \njoin metric m on m.entity_oid = e.\"oid\" AND $__timeFilter(m.time)\nwhere s.seed_oid = $HOST_OID\nand s.scoped_type = 'VIRTUAL_MACHINE'\nand\n  (\n    (s.start <= $__timeFrom() and s.finish <= $__timeTo()) or\n    (s.start >= $__timeFrom() and s.finish <= $__timeTo()) or\n    (s.start >= $__timeFrom() and s.finish >= $__timeTo()) or\n    (s.start <= $__timeFrom() and s.finish >= $__timeTo())\n  )\nand s.finish >= $__timeFrom()\nand s.start <= $__timeTo()\nand m.\"type\" IN ('CPU_READY')\ngroup by e.oid, m.type"
    },
    {
     "rawSql": "select distinct\n\te.oid as \"OID\",\n\tm.\"type\" as \"Type\",\n\tcoalesce(avg(m.utilization), avg(m.consumed))\tas \"Utilization\"\nfrom scope s \njoin entity e on s.scoped_oid = e.\"oid\" \njoin metric m on m.entity_oid = e.\"oid\" AND $__timeFilter(m.time)\nwhere s.seed_oid = $HOST_OID\nand s.scoped_type = 'VIRTUAL_MACHINE'\nand\n  (\n    (s.start <= $__timeFrom() and s.finish <= $__timeTo()) or\n    (s.start >= $__timeFrom() and s.finish <= $__timeTo()) or\n    (s.start >= $__timeFrom() and s.finish >= $__timeTo()) or\n    (s.start <= $__timeFrom() and s.finish >= $__timeTo())\n  )\nand s.finish >= $__timeFrom()\nand s.start <= $__timeTo()\nand m.\"type\" IN ('IO_THROUGHPUT')\ngroup by e.oid, m.type"
    },
    {
     "rawSql": "select distinct\n\te.oid as \"OID\",\n\tm.\"type\" as \"Type\",\n\tcoalesce(avg(m.utilization), avg(m.consumed))\tas \"Utilization\"\nfrom scope s \njoin entity e on s.scoped_oid = e.\"oid\" \njoin metric m on m.entity_oid = e.\"oid\" AND $__timeFilter(m.time)\nwhere s.seed_oid = $HOST_OID\nand s.scoped_type = 'VIRTUAL_MACHINE'\nand\n  (\n    (s.start <= $__timeFrom() and s.finish <= $__timeTo()) or\n    (s.start >= $__timeFrom() and s.finish <= $__timeTo()) or\n    (s.start >= $__timeFrom() and s.finish >= $__timeTo()) or\n    (s.start <= $__timeFrom() and s.finish >= $__timeTo())\n  )\nand s.finish >= $__timeFrom()\nand s.start <= $__timeTo()\nand m.\"type\" IN ('NET_THROUGHPUT')\ngroup by e.oid, m.type"
    }
   ]
  }
 ]
}