{
 "title": "Completed Cloud Actions Tracking - AZURE",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": " Unattached Volume Delete Actions Completed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\n  savings * 24 * 365 / 12\nFROM completed_action ca\nWHERE\n  $__timeFilter(completion_time) AND\n  type = 'DELETE' AND\n  final_state = 'SUCCEEDED'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Unattached Volume Delete Actions completed",
   "type": "table",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Recommend time\",\n  \n  acceptance_time AS \"Acceptance time\",\n  completion_time AS \"Action taken\",\n  type AS \"Action Type\",\n  ca.description as \"Action Details\",\n  savings * 24 * 365 / 12 AS \"Savings\"\n \nFROM completed_action ca\nWHERE\n  $__timeFilter(completion_time) AND\n  type = 'DELETE' AND\n  final_state = 'SUCCEEDED' \nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cloud Volume Tiering Actions completed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\n  savings * 24 * 365 / 12\nFROM completed_action ca\nWHERE\n  $__timeFilter(completion_time) AND\n  type = 'SCALE' AND\n  final_state = 'SUCCEEDED'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cloud Volume Scaling Actions Completed",
   "type": "table",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Recommend time\",\n  \n  acceptance_time AS \"Acceptance time\",\n  completion_time AS \"Action taken\",\n  type AS \"Action Type\",\n  ca.description as \"Action Details\",\n  savings * 24 * 365 / 12 AS \"Savings\"\n \nFROM completed_action ca\nWHERE\n  $__timeFilter(completion_time) AND\n  type = 'SCALE' AND\n  final_state = 'SUCCEEDED' \nORDER BY 1"
    }
   ]
  }
 ]
}