{
 "title": "AAA- Widgets - Completed Actions Summary - On Prem",
 "description": "On-Prem Rightsizing Actions",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CLUSTER_NAME",
    "label": "Cluster",
    "query": "select name from entity e\nwhere \"type\" = 'COMPUTE_CLUSTER'\norder by name"
   },
   {
    "name": "CLUSTER_OID",
    "label": "Cluster OID",
    "query": "select oid from entity e\nwhere \"type\" = 'COMPUTE_CLUSTER'\nand name IN (${CLUSTER_NAME:sqlstring})\norder by name"
   },
   { "name": "VCPU_COST", "label": "Cost of a vCPU ($)", "query": "300" },
   { "name": "VMEM_COST", "label": "Cost of a vMem GB ($)", "query": "80" }
  ]
 },
 "panels": [
  { "title": "Global information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Completed Resize Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VCPU%' OR a.description like '%VMem%') AND\na.final_state = 'SUCCEEDED'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Total Net vCPU difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  (a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float as \"Difference\",\n  a.attrs->'resizeInfo'->'VCPU'->>'unit' as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VCPU%' AND\na.final_state = 'SUCCEEDED'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Total Net vMem difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  (a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float as \"Difference\",\n  a.attrs->'resizeInfo'->'VMEM'->>'unit' as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VMem%' AND\na.final_state = 'SUCCEEDED'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Total vCPU cost difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  ((a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float)*${VCPU_COST} as \"Cost\",\n  a.attrs->'resizeInfo'->'VCPU'->>'unit' as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VCPU%' AND\na.final_state = 'SUCCEEDED'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Total vMem cost difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  ((a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float)*${VMEM_COST}/1024/1024 as \"Cost\",\n  a.attrs->'resizeInfo'->'VMEM'->>'unit' as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VMem%' AND\na.final_state = 'SUCCEEDED'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Scoped information Efficiency/Performance Actions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Completed Efficiency Resize  Actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VCPU%' OR a.description like '%VMem%') AND\na.final_state = 'SUCCEEDED' AND a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Completed Performance Resize  Actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VCPU%' OR a.description like '%VMem%') AND\na.final_state = 'SUCCEEDED' AND a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Completed Efficiency vCPU Resize Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VCPU%') AND\na.final_state = 'SUCCEEDED' AND a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Completed  Efficiency vMem Resize Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VMem%') AND\na.final_state = 'SUCCEEDED' AND a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Completed Performance vCPU Resize Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VCPU%') AND\na.final_state = 'SUCCEEDED' AND a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Completed  Performance vMem Resize Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VMem%') AND\na.final_state = 'SUCCEEDED' AND a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Net vCPU Efficiency difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  (a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float as \"Difference\",\n  a.attrs->'resizeInfo'->'VCPU'->>'unit' as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VCPU%' AND\na.final_state = 'SUCCEEDED' AND a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Net Efficiency vMem  difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  (a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float as \"Difference\",\n  a.attrs->'resizeInfo'->'VMEM'->>'unit' as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VMem%' AND\na.final_state = 'SUCCEEDED' AND a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Net vCPU Performance difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  (a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float as \"Difference\",\n  a.attrs->'resizeInfo'->'VCPU'->>'unit' as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VCPU%' AND\na.final_state = 'SUCCEEDED' AND a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Net Performance vMem  difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  (a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float as \"Difference\",\n  a.attrs->'resizeInfo'->'VMEM'->>'unit' as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VMem%' AND\na.final_state = 'SUCCEEDED' AND a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "vCPU Efficiency cost difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  ((a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float)*${VCPU_COST} as \"Cost\",\n  a.attrs->'resizeInfo'->'VCPU'->>'unit' as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VCPU%' AND\na.final_state = 'SUCCEEDED' AND a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "vMem Efficiency cost difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  ((a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float)*${VMEM_COST}/1000/1000 as \"Cost\",\n  a.attrs->'resizeInfo'->'VMEM'->>'unit' as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VMem%' AND\na.final_state = 'SUCCEEDED' AND a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "vCPU Performance cost difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  ((a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float)*${VCPU_COST} as \"Cost\",\n  a.attrs->'resizeInfo'->'VCPU'->>'unit' as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VCPU%' AND\na.final_state = 'SUCCEEDED' AND a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "vMem Performance cost difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  ((a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float)*${VMEM_COST}/1000/1000 as \"Cost\",\n  a.attrs->'resizeInfo'->'VMEM'->>'unit' as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VMem%' AND\na.final_state = 'SUCCEEDED' AND a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "On-Prem Completed Actions Detail",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \n  a.completion_time as \"Completion Time\",\n  e.\"name\" as \"VM Name\",\n  a.final_state,\n--  a.completion_time,\n  CASE WHEN a.description like '%VCPU%'\n    THEN 'VCPU'\n    ELSE 'VMEM'\n    END as \"Resource\",\n  CASE WHEN ((a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float) > 0 OR ((a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float) > 0\n    THEN 1::integer\n    ELSE -1::integer\n    END as \"Direction\",\n    CASE WHEN a.description like '%VCPU%'\n    THEN (a.attrs->'resizeInfo'->'VCPU'->>'from')::float\n    ELSE (a.attrs->'resizeInfo'->'VMEM'->>'from')::float\n    END as \"from\",\n    CASE WHEN a.description like '%VCPU%'\n    THEN (a.attrs->'resizeInfo'->'VCPU'->>'to')::float\n    ELSE (a.attrs->'resizeInfo'->'VMEM'->>'to')::float\n    END as \"to\",\n  CASE WHEN a.description like '%VCPU%'\n    THEN (a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float\n    ELSE (a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float\n    END as \"Difference\",\n  CASE WHEN a.description like '%VCPU%'\n    THEN a.attrs->'resizeInfo'->'VCPU'->>'unit'\n    ELSE a.attrs->'resizeInfo'->'VMEM'->>'unit'\n    END as \"Unit\"\nFROM completed_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${CLUSTER_OID:sqlstring}) and s.finish > now()\nwhere\n$__timeFilter(a.completion_time) AND\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' \nORDER BY \"VM Name\""
    }
   ]
  }
 ]
}