{
 "title": "Individual VM Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VM",
    "query": "select name from entity where type = 'VIRTUAL_MACHINE' order by 1"
   },
   {
    "name": "VM_OID",
    "query": "select oid from entity where name = '$VM' and type = 'VIRTUAL_MACHINE' order by last_seen DESC limit 1"
   },
   {
    "name": "VM_ENVIRONMENT",
    "query": "SELECT\nCASE environment\nWHEN 'ON_PREM' THEN 'On-Premise'\nWHEN 'CLOUD' Then 'Cloud'\nEND\nFROM entity\nWHERE oid = $VM_OID"
   },
   {
    "name": "VM_OS_TYPE",
    "query": "SELECT\nattrs->>'guest_os_type'\nFROM entity\nWHERE oid = $VM_OID"
   },
   {
    "name": "VM_OS_NAME",
    "query": "SELECT\nattrs->>'guest_os_name'\nFROM entity\nWHERE oid = $VM_OID"
   },
   {
    "name": "VM_NUM_CPUS",
    "query": "SELECT\nattrs->>'num_cpus'\nFROM entity\nWHERE oid = $VM_OID"
   },
   {
    "name": "VM_MEMORY_CURGBCAPACITY",
    "query": "select round(capacity/1024/1024) from metric\nwhere entity_oid = $VM_OID\nand type = 'VMEM'\nORDER by time DESC limit 1"
   },
   {
    "name": "VM_CONNECTED_NETWORKS",
    "query": "SELECT\njsonb_array_elements_text(attrs->'connected_networks') as \"Connected Networks\"\nFROM entity\nWHERE oid = $VM_OID"
   },
   {
    "name": "VM_FIRST_SEEN",
    "query": "SELECT\nfirst_seen\nFROM entity\nWHERE oid = $VM_OID"
   },
   {
    "name": "VM_LAST_SEEN",
    "query": "SELECT\nlast_seen\nFROM entity\nWHERE oid = $VM_OID"
   },
   {
    "name": "VM_STATE",
    "query": "SELECT\nCASE WHEN int_value::entity_state = 'POWERED_ON' THEN 'Powered On' \nELSE 'Powered Off'\nEND\nFROM historical_entity_attrs\nWHERE entity_oid = $VM_OID\nAND type = 'ENTITY_STATE'\nORDER by time DESC limit 1"
   }
  ]
 },
 "panels": [
  {
   "title": "VM Identity Card",
   "type": "text",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n\nThe VM is currently <b>$VM_STATE</b>.\n<br /><br />\n\n<table>\n    <thead>\n        <tr>\n            <td><b>Name</b></td>\n            <td><b>Environment Type</b></td>\n            <td><b>First Seen Date</b></td>\n            <td><b>Last Seen Date</b></td>\n            <td><b>Guest OS</b></td>\n            <td><b>Number of vCPUs</b></td>\n            <td><b>Quantity of vMem</b></td>\n            <td><b>Connected Networks</b></td>\n        </tr>\n    </thead>\n    <tbody>\n        <tr>\n            <td>${VM}</td>\n            <td>${VM_ENVIRONMENT}</td>\n            <td>${VM_FIRST_SEEN}</td>\n            <td>${VM_LAST_SEEN}</td>\n            <td>${VM_OS_TYPE} - ${VM_OS_NAME}</td>\n            <td>${VM_NUM_CPUS}</td>\n            <td>${VM_MEMORY_CURGBCAPACITY} GB</td>\n            <td>${VM_CONNECTED_NETWORKS}</td>\n        </tr>\n    </tbody>\n</table>\n</center>\n\n"
   }
  },
  {
   "title": "Current Group Membership",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "select e.name from \"scope\" s\njoin entity e on s.scoped_oid = e.oid\nwhere s.seed_oid = $VM_OID\nand s.scoped_type = 'GROUP'\nand s.finish >= $__timeTo()\norder by e.name"
    }
   ]
  },
  {
   "title": "vCPU & vMem Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"type\" as metric,\n  utilization as value\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  (type = 'VCPU' or type = 'VMEM') AND\n  entity_oid = $VM_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ready Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  utilization as value,\n  \"type\" as metric\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  (type IN ('CPU_READY','Q1_VCPU','Q2_VCPU','Q4_VCPU','Q8_VCPU','Q16_VCPU','Q32_VCPU','Q64_VCPU')) AND\n  entity_oid = $VM_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Swapping - Ballooning",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "B/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  consumed as value,\n  \"type\" as metric\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  (type IN ('SWAPPING','BALLOONING')) AND\n  entity_oid = $VM_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Storage Latency Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  consumed\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  type = 'STORAGE_LATENCY' AND\n  entity_oid = $VM_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Storage Access Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "KB/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  consumed\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  type = 'STORAGE_ACCESS' AND\n  entity_oid = $VM_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Storage IOPS Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "iops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  consumed\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  type = 'IO_THROUGHPUT' AND\n  entity_oid = $VM_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "KB/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  consumed\nFROM metric\nWHERE\n  $__timeFilter(\"time\") AND\n  type = 'NET_THROUGHPUT' AND\n  entity_oid = $VM_OID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pending Actions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"time\",\n  count(type) as value,\n  CONCAT(category,' - ',type) as metric\nFROM pending_action\nWHERE\n  target_entity_id = $VM_OID\nGROUP BY 1, 3\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Performance actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Time\",\n  description AS \"Description\"\nFROM pending_action\nWHERE\n  (category = 'PERFORMANCE_ASSURANCE' OR category = 'PREVENTION') AND\n  target_entity_id = $VM_OID\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Efficiency actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Time\",\n  description AS \"Description\"\nFROM pending_action\nWHERE\n  (category = 'EFFICIENCY_IMPROVEMENT') AND\n  target_entity_id = $VM_OID\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Compliance actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Time\",\n  description AS \"Description\"\nFROM pending_action\nWHERE\n  (category = 'COMPLIANCE') AND\n  target_entity_id = $VM_OID\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Performance actions",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Time\",\n  description AS \"Description\"\nFROM pending_action\nWHERE\n  (category = 'PERFORMANCE_ASSURANCE' OR category = 'PREVENTION') AND\n  target_entity_id = $VM_OID\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Efficiency actions",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Time\",\n  description AS \"Description\"\nFROM pending_action\nWHERE\n  category = 'EFFICIENCY_IMPROVEMENT' AND\n  target_entity_id = $VM_OID\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Compliance actions",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Time\",\n  description AS \"Description\"\nFROM pending_action\nWHERE\n  category = 'COMPLIANCE' AND\n  target_entity_id = $VM_OID\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Past taken actions",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT\n  description AS \"Description\",\n  acceptance_time AS \"Acceptance Time\",\n  recommendation_time as \"Recommendation Time\",\n  final_state as \"Final State\",\n  \"type\" as \"Type\",\n  category as \"Category\",\n  savings as \"Savings\"\nFROM completed_action\nWHERE\n  $__timeFilter(\"acceptance_time\") AND\n  target_entity_id = $VM_OID\nORDER BY acceptance_time DESC"
    }
   ]
  },
  {
   "title": "Associated Host(s) Performance - CPU & Mem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select\n  m.\"time\" as \"time\",\n  m.utilization as value,\n  CONCAT(m.\"type\",' - ',e.name) as metric\nfrom \"scope\" s\njoin metric m on m.entity_oid = s.scoped_oid\njoin entity e on m.entity_oid = e.\"oid\" \nwhere\n$__timeFilter(m.\"time\")\nand s.seed_oid = $VM_OID\nand m.\"type\" IN ('CPU', 'MEM')\nand s.scoped_type = 'PHYSICAL_MACHINE'\nand m.\"time\" >= s.\"start\" and m.\"time\" <= s.finish\norder by m.\"time\", metric"
    }
   ]
  },
  {
   "title": "Associated Host(s) Performance - Ready Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select\n  m.\"time\" as \"time\",\n  m.utilization as value,\n  CONCAT(m.\"type\",' - ',e.name) as metric\nfrom \"scope\" s\njoin metric m on m.entity_oid = s.scoped_oid\njoin entity e on m.entity_oid = e.\"oid\" \nwhere\n$__timeFilter(m.\"time\")\nand s.seed_oid = $VM_OID\nand m.\"type\" IN ('Q1_VCPU','Q2_VCPU','Q4_VCPU','Q8_VCPU','Q16_VCPU','Q32_VCPU','Q64_VCPU')\nand s.scoped_type = 'PHYSICAL_MACHINE'\nand m.\"time\" >= s.\"start\" and m.\"time\" <= s.finish\norder by m.\"time\", metric"
    }
   ]
  }
 ]
}