{
 "title": "Datacenter & Cluster Overview - CPU, Mem, Storage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": "SELECT DISTINCT name as __text\n              ,oid as __value \n   FROM entity\n WHERE type = 'DATACENTER'\n    AND (first_seen, last_seen) OVERLAPS ($__timeFrom(), $__timeTo())"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "SELECT DISTINCT SPLIT_PART(name, '/', 2) as __text,\n               oid as __value\n    FROM entity e\n    JOIN scope s on s.seed_oid = e.oid\n  WHERE type = 'COMPUTE_CLUSTER'\n      AND s.scoped_type = 'DATACENTER'\n      AND (start, finish) OVERLAPS ($__timeFrom(), $__timeTo())\n      AND (first_seen, last_seen) OVERLAPS ($__timeFrom(), $__timeTo())\n      AND CASE WHEN $datacenter = '0' THEN true ELSE s.scoped_oid = $datacenter END\n  "
   },
   {
    "name": "hostThreshold",
    "label": "Threshold",
    "query": "SELECT generate_series || '%' as __text,\n               generate_series*.01 as __value\n  FROM generate_series(30,100,5)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Overview",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with clusters_by_datacenter as (\n    SELECT DISTINCT e.oid as cluster_oid\n      FROM entity e\n      JOIN scope s on (s.seed_oid = e.oid)\n     WHERE e.type = 'COMPUTE_CLUSTER'\n       AND s.scoped_type = 'DATACENTER'\n       AND CASE WHEN $datacenter = '0' THEN true ELSE s.scoped_oid = $datacenter END\n       AND CASE WHEN $cluster = '0' THEN true ELSE e.oid = $cluster END\n),\n\nvms_by_cluster AS (\n  SELECT DISTINCT on (e.oid) s1.scoped_oid as cluster_oid\n        ,e.oid as vm_oid\n        ,(e.attrs -> 'num_cpus')::int as vm_vcpus\n      FROM entity e\n      JOIN scope s1 ON (s1.seed_oid = e.oid)\n     WHERE e.type = 'VIRTUAL_MACHINE'\n       AND (s1.scoped_type = 'COMPUTE_CLUSTER')\n       AND (s1.scoped_oid in (select cluster_oid from clusters_by_datacenter))\n       AND (e.first_seen, e.last_seen) OVERLAPS ($__timeFrom(), $__timeTo())\n       AND (s1.start, s1.finish) OVERLAPS ($__timeFrom(), $__timeTo())\n),\n\npms_by_cluster as (\n    SELECT DISTINCT ON (e.oid)\n        g.name as cluster_name,\n        g.oid as cluster_oid,\n        e.oid as pm_oid,\n        (e.attrs -> 'num_cpus')::int as pm_cpus\n      FROM entity e\n      JOIN scope s1 ON (s1.seed_oid = e.oid)\n      JOIN entity g ON (g.oid = s1.scoped_oid)\n     WHERE e.type = 'PHYSICAL_MACHINE'\n       AND (s1.scoped_type = 'COMPUTE_CLUSTER')\n       AND (s1.scoped_oid in (select cluster_oid from clusters_by_datacenter))\n       AND (e.first_seen, e.last_seen) OVERLAPS ($__timeFrom(), $__timeTo())\n       AND (s1.start, s1.finish) OVERLAPS ($__timeFrom(), $__timeTo())\n),\n\ncluster_stats as (\n    SELECT cluster_oid\n          ,SUM(cpu_capacity) as cpu_capacity\n          ,SUM(cpu_used) as cpu_used\n          ,SUM(cpu_available) as cpu_available\n          ,SUM(cpu_used) / SUM(cpu_capacity) as cpu_util\n     from \n        (SELECT entity_oid as pm_oid\n               ,AVG(current) as cpu_used\n               ,AVG(capacity) as cpu_capacity\n               ,AVG(capacity - current) as cpu_available\n          FROM metric\n         WHERE type = 'CPU'\n           AND $__timeFilter(time)\n           AND consumed is NULL\n         GROUP BY 1) as pm_stats\n    JOIN pms_by_cluster on pms_by_cluster.pm_oid = pm_stats.pm_oid\n   GROUP BY 1\n),\n\npm_counts as (\n    SELECT cluster_oid\n          ,COUNT(DISTINCT pm_oid) as pm_count\n          ,SUM(pm_cpus) as cluster_cpus\n      FROM pms_by_cluster\n     GROUP BY 1\n),\n\nvm_counts as (\n    SELECT cluster_oid\n          ,COUNT(DISTINCT vm_oid) as vm_count\n          ,SUM(vm_vcpus) as cluster_vcpus\n      FROM vms_by_cluster\n     GROUP BY 1\n)\n\nSELECT LEFT(pms_by_cluster.cluster_name, 3) as \"Location\", \n       SPLIT_PART(pms_by_cluster.cluster_name, '/', 1) as \"Datacenter\",\n       SPLIT_PART(pms_by_cluster.cluster_name, '/', 2) as \"Cluster Name\",\n       MAX(pm_count) \"# Hosts\",\n       MAX(vm_count) \"# VMs\",\n       MAX(cpu_capacity) as \"CPU Capacity\",\n       MAX(cpu_used) as \"CPU Used\",\n       MAX(cpu_available) as \"CPU Available\",\n       MAX(cpu_util) as \"CPU Utilization\",\n       $hostThreshold::numeric as \"CPU Threshold %\",\n       ((1 - $hostThreshold)::numeric * SUM(cpu_capacity)) as \"CPU Ideal Available\",\n       MAX((pm_count::numeric - 1) / pm_count) \"N-1 CPU Threshold\",\n       MAX((1 - (pm_count::numeric - 1) / pm_count)) * SUM(cpu_capacity) \"N-1 Ideal Available CPU\",\n       MAX((pm_count::numeric - 2) / pm_count) \"N-2 CPU Threshold\",\n       MAX((1 - (pm_count::numeric - 2) / pm_count)) * SUM(cpu_capacity) \"N-2 Ideal Available CPU\",\n       AVG(pm_cpus) \"Avg CPUs per Host\",\n       MAX(vm_vcpus::numeric/pm_cpus) \"Max vCPU Ratio in Cluster\",\n       MAX(cluster_cpus) \"CPUs per Cluster\",\n       MAX(cluster_vcpus) as \"vCPUs\"\n  FROM cluster_stats, pm_counts, vm_counts, pms_by_cluster, vms_by_cluster\n WHERE vm_counts.cluster_oid = cluster_stats.cluster_oid\n   AND pm_counts.cluster_oid = cluster_stats.cluster_oid\n   AND pms_by_cluster.cluster_oid = cluster_stats.cluster_oid\n   and vms_by_cluster.cluster_oid = pms_by_cluster.cluster_oid\n GROUP BY 1, 2, 3"
    }
   ]
  },
  {
   "title": "Memory Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "with clusters_by_datacenter as (\n    SELECT DISTINCT e.oid as cluster_oid\n      FROM entity e\n      JOIN scope s on (s.seed_oid = e.oid)\n     WHERE e.type = 'COMPUTE_CLUSTER'\n       AND s.scoped_type = 'DATACENTER'\n       AND CASE WHEN $datacenter = '0' THEN true ELSE s.scoped_oid = $datacenter END\n       AND CASE WHEN $cluster = '0' THEN true ELSE e.oid = $cluster END\n),\n\nvms_by_cluster AS (\n  SELECT s1.scoped_oid as cluster_oid\n        ,count(distinct e.oid) as vm_count\n      FROM entity e\n      JOIN scope s1 ON (s1.seed_oid = e.oid)\n     WHERE e.type = 'VIRTUAL_MACHINE'\n       AND (s1.scoped_type = 'COMPUTE_CLUSTER')\n       AND (s1.scoped_oid in (select cluster_oid from clusters_by_datacenter))\n       AND (e.first_seen, e.last_seen) OVERLAPS ($__timeFrom(), $__timeTo())\n       AND (s1.start, s1.finish) OVERLAPS ($__timeFrom(), $__timeTo())\n     group by 1\n),\n\npms_by_cluster as (\n    SELECT DISTINCT ON (e.oid)\n        g.name as cluster_name,\n        g.oid as cluster_oid,\n        e.oid as pm_oid\n      FROM entity e\n      JOIN scope s1 ON (s1.seed_oid = e.oid)\n      JOIN entity g ON (g.oid = s1.scoped_oid)\n     WHERE e.type = 'PHYSICAL_MACHINE'\n       AND (s1.scoped_type = 'COMPUTE_CLUSTER')\n       AND (s1.scoped_oid in (select cluster_oid from clusters_by_datacenter))\n       AND (e.first_seen, e.last_seen) OVERLAPS ($__timeFrom(), $__timeTo())\n       AND (s1.start, s1.finish) OVERLAPS ($__timeFrom(), $__timeTo())\n),\n\ncluster_stats as (\n    select cluster_oid\n          ,count(distinct pm_stats.pm_oid) as pm_count\n          ,SUM(mem_used) as mem_used\n          ,SUM(mem_capacity) as mem_capacity \n          ,SUM(mem_available) as mem_available \n          ,SUM(mem_used) / SUM(mem_capacity) as mem_util\n    from\n        (SELECT entity_oid as pm_oid,\n                AVG(current) as mem_used,\n                AVG(capacity) as mem_capacity,\n                AVG(capacity - current) as mem_available\n           FROM metric\n          WHERE type = 'MEM'\n            AND $__timeFilter(time)\n            AND consumed is NULL\n          GROUP BY 1) as pm_stats\n     join pms_by_cluster on pms_by_cluster.pm_oid = pm_stats.pm_oid\n    group by 1\n)\n\nSELECT LEFT(pms_by_cluster.cluster_name, 3) as \"Location\", \n       SPLIT_PART(pms_by_cluster.cluster_name, '/', 1) as \"Datacenter\",\n       SPLIT_PART(pms_by_cluster.cluster_name, '/', 2) as \"Cluster Name\",\n       MAX(pm_count) \"# Hosts\",\n       MAX(vm_count) \"# VMs\",\n       MAX(mem_capacity)/1024/1024 as \"MEM Capacity\",\n       MAX(mem_used)/1024/1024 as \"MEM Used\",\n       MAX(mem_available)/1024/1024 as \"MEM Available\",\n       MAX(mem_util) as \"MEM Utilization %\",\n       $hostThreshold::numeric as \"MEM Threshold %\",\n       ((1 - $hostThreshold)::numeric * MAX(MEM_capacity))/1024/1024 as \"MEM Ideal Available\",\n       MAX((pm_count::numeric - 1) / pm_count) \"N-1 MEM Threshold %\",\n       MAX((1 - (pm_count::numeric - 1) / pm_count)) * MAX(MEM_capacity)/1024/1024 \"N-1 Ideal Available MEMORY\",\n       MAX((pm_count::numeric - 2) / pm_count) \"N-2 MEM Threshold %\",\n       MAX((1 - (pm_count::numeric - 2) / pm_count)) * MAX(MEM_capacity)/1024/1024 \"N-2 Ideal Available MEMORY\"\n  FROM vms_by_cluster, pms_by_cluster, cluster_stats\n WHERE vms_by_cluster.cluster_oid = pms_by_cluster.cluster_oid\n   AND cluster_stats.cluster_oid = pms_by_cluster.cluster_oid\n GROUP BY 1, 2, 3"
    }
   ]
  },
  {
   "title": "Storage Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "with clusters_by_datacenter as (\n    SELECT DISTINCT e.oid as cluster_oid\n      FROM entity e\n      JOIN scope s on (s.seed_oid = e.oid)\n     WHERE e.type = 'COMPUTE_CLUSTER'\n       AND s.scoped_type = 'DATACENTER'\n       AND CASE WHEN $datacenter = '0' THEN true ELSE s.scoped_oid = $datacenter END\n       AND CASE WHEN $cluster = '0' THEN true ELSE e.oid = $cluster END\n),\n\nvms_and_hosts_datastore AS (\n  SELECT e.oid as storage_oid\n        ,count(distinct s1.scoped_oid) as vm_count\n        ,count(distinct s2.scoped_oid) as pm_count\n      FROM entity e\n      JOIN scope s1 ON (s1.seed_oid = e.oid)\n      JOIN scope s2 ON (s2.seed_oid = e.oid)\n     WHERE e.type = 'STORAGE'\n       AND (s1.scoped_type = 'VIRTUAL_MACHINE')\n       AND (s2.scoped_type = 'PHYSICAL_MACHINE')\n       AND (e.first_seen, e.last_seen) OVERLAPS ($__timeFrom(), $__timeTo())\n       AND (s1.start, s1.finish) OVERLAPS ($__timeFrom(), $__timeTo())\n       AND (s1.start, s1.finish) OVERLAPS ($__timeFrom(), $__timeTo())\n     group by 1\n),\n\nstorages_by_cluster as (\n    SELECT g.name as cluster_name,\n        g.oid as cluster_oid,\n        e.oid as storage_oid,\n        e.name as datastore_name\n      FROM entity e\n      JOIN scope s1 ON (s1.seed_oid = e.oid)\n      JOIN entity g ON (g.oid = s1.scoped_oid)\n     WHERE e.type = 'STORAGE'\n       AND (s1.scoped_type = 'COMPUTE_CLUSTER')\n       AND (s1.scoped_oid in (select cluster_oid from clusters_by_datacenter))\n       AND (e.first_seen, e.last_seen) OVERLAPS ($__timeFrom(), $__timeTo())\n       AND (s1.start, s1.finish) OVERLAPS ($__timeFrom(), $__timeTo())\n     group by 1,2,3\n),\n\ncluster_stats as (\n    SELECT cluster_oid\n          ,cluster_name\n          ,storage_stats.storage_oid\n          ,datastore_name\n          ,COUNT(distinct storages_by_cluster.storage_oid) as ds_count\n          ,SUM(stor_cap) as storage_capacity\n          ,SUM(stor_prov) as storage_provisioned\n          ,SUM(stor_used) as storage_amount\n          ,SUM(stor_used) / SUM(stor_cap) as storage_util\n      FROM (\n        SELECT entity_oid as storage_oid\n              ,max(metric.capacity) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') AS stor_cap\n              ,max(metric.current) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') AS stor_prov\n              ,max(metric.current) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') AS stor_used\n          FROM metric\n         WHERE type in ('STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n           AND $__timeFilter(time)\n           AND consumed is NULL\n         GROUP BY 1) as storage_stats\n    JOIN storages_by_cluster ON storage_stats.storage_oid = storages_by_cluster.storage_oid\n   GROUP BY 1, 2, 3, 4 \n),\n\nwasted_storage as (\n  SELECT storage_oid,\n         count(*) as num_wasted_files,\n         sum(file_size_kb)/1024 as total_wasted_mb\n    FROM wasted_file\n   WHERE file_size_kb > 0\n   GROUP BY 1\n)\n\nSELECT SPLIT_PART(cluster_stats.cluster_name, '/', 1) as \"Datacenter\",\n       SPLIT_PART(cluster_stats.cluster_name, '/', 2) as \"Cluster Name\",\n       datastore_name as \"DataStore Name\",\n       vm_count as \"Datastore # VMs\",\n       pm_count as \"Datastore # Hosts\",\n       storage_capacity/1024 as \"Storage Capacity\",\n       storage_provisioned/1024 as \"Storage Provisioned\",\n       storage_amount/1024 as \"Storage Used\",\n       storage_util*100 as \"Storage Used %\",\n       (1 - storage_util)*100 as \"Storage Free %\",\n       num_wasted_files as \"# Wasted Files\",\n       total_wasted_mb/1024 as \"Storage Wasted\"\n  FROM cluster_stats\n  JOIN vms_and_hosts_datastore on cluster_stats.storage_oid = vms_and_hosts_datastore.storage_oid\n  JOIN wasted_storage on wasted_storage.storage_oid = cluster_stats.storage_oid"
    }
   ]
  }
 ]
}