{
 "title": "Kubernetes Container Usage - with text search",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CLUSTER",
    "label": "Cluster",
    "query": "select distinct\n    name AS __text,\n    oid AS __value\nfrom entity\nwhere\n    type = 'CONTAINER_PLATFORM_CLUSTER'\n    and ($__timeFrom(),$__timeTo()) OVERLAPS (first_seen, last_seen)\norder by 1"
   },
   {
    "name": "NAMESPACE",
    "label": "Namespace",
    "query": "select distinct\n    e.name AS __text,\n    e.oid AS __value\nfrom \"scope\" s \njoin entity e on s.scoped_oid = e.\"oid\"\nwhere\n    s.scoped_type = 'NAMESPACE'\n    and ($__timeFrom(),$__timeTo()) OVERLAPS (e.first_seen, e.last_seen)\n    and s.seed_oid IN (${CLUSTER})\n    and ($__timeFrom(),$__timeTo()) OVERLAPS (s.start, s.finish)\norder by 1"
   },
   { "name": "TAG_SEARCH", "label": "Tag" },
   {
    "name": "CONTAINER",
    "label": "Container",
    "query": "SELECT distinct\n  ec.name as __text,\n  s.scoped_oid as __value\nFROM entity ecs\njoin scope s on s.seed_oid = ecs.oid and s.scoped_type = 'CONTAINER'\njoin entity ec on s.scoped_oid = ec.oid\njoin scope sn on sn.scoped_oid = ec.oid and sn.seed_oid IN (${NAMESPACE})\nWHERE\n  ecs.type = 'CONTAINER_SPEC'\n  and ($__timeFrom(),$__timeTo()) OVERLAPS (ec.first_seen, ec.last_seen)\n  and ($__timeFrom(),$__timeTo()) OVERLAPS (s.start, s.finish) \n  AND replace(translate(ecs.attrs->>'tags', '{}[]\"', ''), ',', ' --- ') like '%${TAG_SEARCH}%'\nORDER BY 1"
   },
   {
    "name": "TAG",
    "label": "Tag",
    "query": "select\n  concat(tag.key, ': ', translate(tag.value, '{}[]\"', '')) as \"tag\"\nFROM entity e\ncross join jsonb_each_text(e.attrs->'tags') as tag(key, value)\nWHERE\n  ($__timeFrom(),$__timeTo()) OVERLAPS (e.first_seen, e.last_seen)\n  AND e.type = 'CONTAINER_SPEC'\nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "vCPU (usage vs request)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  m.utilization as value,\n  e.name as metric\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\"\nWHERE\n  $__timeFilter(m.time)\n  AND m.entity_type = 'CONTAINER'\n  AND m.type = 'VCPU_REQUEST'\n  AND m.entity_oid IN (${CONTAINER})\n  AND m.provider_oid is null\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "vCPU Request Capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "millicores" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  m.capacity as value,\n  e.name as metric\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\"\nWHERE\n  $__timeFilter(m.time)\n  AND m.entity_type = 'CONTAINER'\n  AND m.type = 'VCPU_REQUEST'\n  AND m.entity_oid IN (${CONTAINER})\n  AND m.provider_oid is null\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "vCPU (usage vs limit)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  m.utilization as value,\n  e.name as metric\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\"\nWHERE\n  $__timeFilter(m.time)\n  AND m.entity_type = 'CONTAINER'\n  AND m.type = 'VCPU'\n  AND m.entity_oid IN (${CONTAINER})\n  AND m.provider_oid is null\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "vCPU Limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "millicores" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  m.capacity as value,\n  e.name as metric\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\"\nWHERE\n  $__timeFilter(m.time)\n  AND m.entity_type = 'CONTAINER'\n  AND m.type = 'VCPU'\n  AND m.entity_oid IN (${CONTAINER})\n  AND m.provider_oid is null\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "vMem (usage vs request)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  m.utilization as value,\n  e.name as metric\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\"\nWHERE\n  $__timeFilter(m.time)\n  AND m.entity_type = 'CONTAINER'\n  AND m.type = 'VMEM_REQUEST'\n  AND m.entity_oid IN (${CONTAINER})\n  AND m.provider_oid is null\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "vMem Request Capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  m.capacity as value,\n  e.name as metric\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\"\nWHERE\n  $__timeFilter(m.time)\n  AND m.entity_type = 'CONTAINER'\n  AND m.type = 'VMEM_REQUEST'\n  AND m.entity_oid IN (${CONTAINER})\n  AND m.provider_oid is null\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "vMem (usage vs limit)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  m.utilization as value,\n  e.name as metric\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\"\nWHERE\n  $__timeFilter(m.time)\n  AND m.entity_type = 'CONTAINER'\n  AND m.type = 'VMEM'\n  AND m.entity_oid IN (${CONTAINER})\n  AND m.provider_oid is null\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "vMem Limit Capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  m.capacity as value,\n  e.name as metric\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\"\nWHERE\n  $__timeFilter(m.time)\n  AND m.entity_type = 'CONTAINER'\n  AND m.type = 'VMEM'\n  AND m.entity_oid IN (${CONTAINER})\n  AND m.provider_oid is null\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "CPU Throttling (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  m.utilization as value,\n  e.name as metric\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\"\nWHERE\n  $__timeFilter(m.time)\n  AND m.entity_type = 'CONTAINER'\n  AND m.type = 'VCPU_THROTTLING'\n  AND m.entity_oid IN (${CONTAINER})\n  AND m.provider_oid is null\nORDER BY 1\n"
    }
   ]
  }
 ]
}