{
 "title": "On-Prem: Pending Resize Actions Summary by VM Group with Costs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "GROUP_NAME",
    "label": "Group Name",
    "query": "select name\nfrom entity e \nwhere e.\"type\" = 'GROUP'\nand attrs->'member_types' ? 'VIRTUAL_MACHINE'\nand e.last_seen > now()\norder by name"
   },
   {
    "name": "GROUP_OID",
    "label": "Group OID",
    "query": "select oid from entity e\nwhere e.\"type\" = 'GROUP'\nand e.attrs->'member_types' ? 'VIRTUAL_MACHINE'\nand e.last_seen > now()\nand e.name IN (${GROUP_NAME:sqlstring})\norder by e.name"
   },
   { "name": "VCPU_COST", "label": "Cost of a vCPU ($)", "query": "10" },
   { "name": "VMEM_COST", "label": "Cost of a vMem GB ($)", "query": "20" }
  ]
 },
 "panels": [
  { "title": "Global information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total vMEM Resize Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VCPU%' OR a.description like '%VMem%')\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Total vCPU Resize Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VCPU%' OR a.description like '%VMem%')\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Total Net vMem difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  (a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float as \"Difference\",\n  a.attrs->'resizeInfo'->'VMEM'->>'unit' as \"Unit\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VMem%'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Total Net vCPU difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  (a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float as \"Difference\",\n  a.attrs->'resizeInfo'->'VCPU'->>'unit' as \"Unit\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VCPU%'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Total vCPU cost difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  ((a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float)*${VCPU_COST} as \"Cost\",\n  a.attrs->'resizeInfo'->'VCPU'->>'unit' as \"Unit\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VCPU%'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Total vMem cost difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  e.\"name\" as \"VM Name\",\n  ((a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float)*${VMEM_COST}/(1000*1000) as \"Cost\",\n  a.attrs->'resizeInfo'->'VMEM'->>'unit' as \"Unit\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VMem%'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Scoped information Efficiency / Performance Actions Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Pending Resize Efficiency Actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VCPU%' OR a.description like '%VMem%')\nAND  a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Pending Performance Assurance Resize Actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VCPU%' OR a.description like '%VMem%')\nAND  a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Pending vCPU Resize Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VCPU%') \nAND  a.category = 'EFFICIENCY_IMPROVEMENT'\n\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Pending vMem Resize Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VMem%')\nAND  a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Pending vCPU Resize Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VCPU%')\nAND  a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Pending vMem Resize Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  a.description as \"Description\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\n(a.description like '%VMem%')\nAND  a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Net vCPU difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  (a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float as \"Difference\",\n  a.attrs->'resizeInfo'->'VCPU'->>'unit' as \"Unit\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VCPU%'\nAND  a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Net vMem difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  (a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float as \"Difference\",\n  a.attrs->'resizeInfo'->'VMEM'->>'unit' as \"Unit\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VMem%'\nAND  a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Net vCPU difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  (a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float as \"Difference\",\n  a.attrs->'resizeInfo'->'VCPU'->>'unit' as \"Unit\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VCPU%'\nAND  a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "Net vMem difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  (a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float as \"Difference\",\n  a.attrs->'resizeInfo'->'VMEM'->>'unit' as \"Unit\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VMem%'\nAND  a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "vCPU cost difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  ((a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float)*${VCPU_COST} as \"Cost\",\n  a.attrs->'resizeInfo'->'VCPU'->>'unit' as \"Unit\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VCPU%'\nAND  a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "vMem cost difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  ((a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float)*${VMEM_COST}/(1000*1000) as \"Cost\",\n  a.attrs->'resizeInfo'->'VMEM'->>'unit' as \"Unit\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VMem%'\nAND  a.category = 'EFFICIENCY_IMPROVEMENT'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "vCPU cost difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  ((a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float)*${VCPU_COST} as \"Cost\",\n  a.attrs->'resizeInfo'->'VCPU'->>'unit' as \"Unit\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VCPU%'\nAND  a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "vMem cost difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n  ((a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float)*${VMEM_COST}/(1000*1000) as \"Cost\",\n  a.attrs->'resizeInfo'->'VMEM'->>'unit' as \"Unit\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE' AND\na.description like '%VMem%'\nAND  a.category = 'PERFORMANCE_ASSURANCE'\nORDER BY \"VM Name\""
    }
   ]
  },
  {
   "title": "On-Prem Pending Actions",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.\"name\" as \"VM Name\",\n--  a.recommendation_time,\n  CASE WHEN a.description like '%VCPU%'\n    THEN 'VCPU'\n    ELSE 'VMEM'\n    END as \"Resource\",\n  CASE WHEN ((a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float) > 0 OR ((a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float) > 0\n    THEN 1::integer\n    ELSE -1::integer\n    END as \"Direction\",\n  CASE WHEN a.description like '%VCPU%'\n    THEN (a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float\n    ELSE (a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float\n    END as \"Difference\",\n  CASE WHEN a.description like '%VCPU%'\n    THEN a.attrs->'resizeInfo'->'VCPU'->>'unit'\n    ELSE a.attrs->'resizeInfo'->'VMEM'->>'unit'\n    END as \"Unit\",\n   a.category as \"Action Type\"\nFROM pending_action a\njoin entity e on a.target_entity_id = e.\"oid\"\njoin scope s on s.scoped_oid = e.oid AND s.seed_oid IN (${GROUP_OID:sqlstring}) and s.finish > now()\nwhere\na.\"type\" = 'RESIZE' AND\ne.environment = 'ON_PREM' AND\ne.\"type\" = 'VIRTUAL_MACHINE'\nORDER BY \"VM Name\""
    }
   ]
  }
 ]
}