{
 "title": "Cloud Wasted Storage Actions",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Unattached Cloud Volumes Summary",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  pa.savings * 24 * 365 / 12 as \"Savings/mo\"\nFROM pending_action pa\nJOIN entity e ON e.\"oid\" = pa.target_entity_id \nWHERE\n  $__timeFilter(pa.recommendation_time)\n  AND e.environment = 'CLOUD'\n  AND e.\"type\" =  'VIRTUAL_VOLUME'\n  AND pa.\"type\" = 'DELETE'\nORDER BY 1"
    },
    { "rawSql": "SELECT 1" }
   ]
  },
  {
   "title": "Pending Cloud Delete Actions - Unattached Cloud Volumes",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  pa.recommendation_time as \"Recommendation Time\",\n  INITCAP(pa.\"type\"::text) as \"Action Type\",\n  e.name as \"Entity Name\",\n  pa.attrs->'deleteInfo'->'fileSize' as \"FileSize (MB)\",\n  pa.attrs->'deleteInfo'->'unattachedDays' as \"Days Unattached\",\n  CASE\n    WHEN e.\"type\" = 'VIRTUAL_MACHINE' THEN 'Virtual Machine'\n    WHEN e.\"type\" = 'VIRTUAL_VOLUME' THEN 'Virtual Volume'\n    ELSE 'Unknown'\n  END as \"Entity Type\",\n  e.attrs->>'vendor_id' as \"Vendor ID\",\n  pa.description as \"Description\",\n  pa.savings * 24 * 365 / 12 as \"Savings/mo\"\nFROM pending_action pa\nJOIN entity e ON e.\"oid\" = pa.target_entity_id \nWHERE\n  $__timeFilter(pa.recommendation_time)\n  AND e.environment = 'CLOUD'\n  AND e.\"type\" IN ('VIRTUAL_MACHINE', 'VIRTUAL_VOLUME')\n  AND pa.\"type\" = 'DELETE'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cloud Delete Actions completed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\n  savings * 24 * 365 / 12\nFROM completed_action ca\nWHERE\n  $__timeFilter(completion_time) AND\n  final_state = 'SUCCEEDED' AND\n  type = 'DELETE'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cloud Delete Actions completed details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  recommendation_time AS \"Recommend time\",\n  \n  acceptance_time AS \"Acceptance time\",\n  completion_time AS \"Action taken\",\n   ca.description as \"Action Details\",\n  savings * 24 * 365 / 12 AS \"Savings\"\n \nFROM completed_action ca\nWHERE\n  $__timeFilter(completion_time) AND\n  final_state = 'SUCCEEDED' AND\n  type = 'DELETE'\nORDER BY 1"
    }
   ]
  }
 ]
}